/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CredentialsindexImport } from './routes/credentials index'
import { Route as CredentialsImport } from './routes/credentials'
import { Route as IndexImport } from './routes/index'
import { Route as CredentialsEditIdImport } from './routes/credentials.edit.$id'

// Create/Update Routes

const CredentialsindexRoute = CredentialsindexImport.update({
  path: '/credentials index',
  getParentRoute: () => rootRoute,
} as any)

const CredentialsRoute = CredentialsImport.update({
  path: '/credentials',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CredentialsEditIdRoute = CredentialsEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => CredentialsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/credentials': {
      preLoaderRoute: typeof CredentialsImport
      parentRoute: typeof rootRoute
    }
    '/credentials index': {
      preLoaderRoute: typeof CredentialsindexImport
      parentRoute: typeof rootRoute
    }
    '/credentials/edit/$id': {
      preLoaderRoute: typeof CredentialsEditIdImport
      parentRoute: typeof CredentialsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CredentialsRoute.addChildren([CredentialsEditIdRoute]),
  CredentialsindexRoute,
])

/* prettier-ignore-end */
